name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build -DALGLOG_BUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config Release

    - name: Run Test (Windows)
      if: runner.os == 'Windows'
      run: ${{github.workspace}}\build\test\Release\AlgLogTest.exe

    - name: Run Test (Unix)
      if: runner.os != 'Windows'
      run: ${{github.workspace}}/build/test/AlgLogTest
